language: node_js
node_js:
    - 5.12
script: "npm run coverage"
after_script: "cat ./test/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
notifications:
    email:
        on_success: never
        on_failure: change
